export const DASHBOARD = "Dashboard";
export const INCIDENT = "Incident";
export const DAMAGELOSS = "Damage";
export const RISKINFO = "Risk Info";
export const REALTIME = "Realtime";
export const REPORT = "Report";
export const DATA = "Data";
export const SITUATION = "Situation";
export const FEEDBACK = "Feedback";
